# Generated by Django 3.2.12 on 2024-02-19 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20240219_1907'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorical',
            new_name='Category',
        ),
    ]
