# Generated by Django 3.2.12 on 2024-02-19 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20240219_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='posts',
        ),
    ]
